### ISSUE TITLE
ローカルPC上で動作するサービスを外部公開したい

### ISSUE THREAD

**Issue by ckym02** [koyama-c/sample-app#1]
#### ngrok を使用する
- 複数ポートのために設定ファイルを読み込みたかったので、Dockerfileを用意し全ての tunnel が起動されるようにする
- http://localhost:4040 もしくは http://localhost:4040/status にアクセス
- docker-compose.yml
```yml
  ngrok:
    build: ./ngrok
    container_name: ngrok
    ports:
      - 4040:4040
 ```
- ngrock/Dockerfile
```Dockerfile
FROM alpine:3.9

RUN set -x && \
    apk add --no-cache -t .deps ca-certificates && \
    # Install glibc on Alpine (required by docker-compose) from
    # https://github.com/sgerrand/alpine-pkg-glibc
    # See also https://github.com/gliderlabs/docker-alpine/issues/11
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk && \
    apk add glibc-2.29-r0.apk && \
    rm glibc-2.29-r0.apk && \
    apk del --purge .deps

RUN set -x \
    # Install ngrok (latest official stable from https://ngrok.com/download).
    && apk add --no-cache curl \
    && curl -Lo /ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip \
    && unzip -o /ngrok.zip -d /bin \
    && rm -f /ngrok.zip \
    # Create non-root user.
    && adduser -h /home/ngrok -D -u 6737 ngrok

RUN  ngrok --version

# Add config script.
COPY --chown=ngrok ./ngrok.yml /home/ngrok/.ngrok2/
COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh


USER ngrok
ENV USER=ngrok

EXPOSE 4040
ENTRYPOINT ["/entrypoint.sh"]
```
- ngrok/entrypoint.sh
```sh
#!/bin/sh -e

if [ -n "$@" ]; then
  exec "$@"
fi

ARGS="ngrok start --all -config=/home/ngrok/.ngrok2/ngrok.yml"

set -x
exec $ARGS
```
- ngrok/ngrok.yml
  - https://ngrok.com/docs/ngrok-agent/config#config-tunnels
```yml
authtoken: *****
web_addr: 0.0.0.0:4040
tunnels:
  app:
    proto: http
    addr: host.docker.internal:3000
  liff-inspector:
    proto: http
    addr: host.docker.internal:9222
```
